language: java

jdk:
  - oraclejdk8

before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.zip
- unzip -qq apache-maven-3.0.5-bin.zip
- export M2_HOME=$PWD/apache-maven-3.0.5
- export PATH=$M2_HOME/bin:$PATH

install: true
script:
- mvn -U clean package 
  
after_success:
- mvn jacoco:report coveralls:report
